# Generated by Django 4.1.7 on 2023-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Text', models.TextField(blank=True)),
                ('Announcement_image', models.ImageField(blank=True, upload_to='uploadfiles/Announcementİmage')),
                ('Announcement_file', models.FileField(blank=True, upload_to='uploadfiles/Announcementfile')),
                ('Slug', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
    ]
