# Generated by Django 4.1.7 on 2023-02-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('genaralApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='Site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Site', to='sites.site', verbose_name='Site'),
        ),
    ]
