# Generated by Django 4.1.7 on 2023-02-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genaralApp', '0003_alter_domain_subdomainname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='LanguageCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='LanguageName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='TemplateName',
            field=models.CharField(max_length=80),
        ),
    ]
