# Generated by Django 4.1.7 on 2023-02-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genaralApp', '0004_alter_domain_isactive_alter_language_isactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='SubdomainName',
            new_name='DomainName',
        ),
    ]
