# Generated by Django 4.1.7 on 2023-02-20 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('Cover', models.ImageField(blank=True, upload_to='uploadfiles/Albüm', verbose_name='Albüm Kapağı')),
                ('Slug', models.CharField(max_length=1000)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsActive', models.BooleanField(default=True, verbose_name='Aktif')),
                ('PublishedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'db_table': 'PhotoGallery',
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, upload_to='uploadfiles/Albümİmage', verbose_name='Fotoğraf')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsActive', models.BooleanField(default=True, verbose_name='Aktif')),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photogallery.photogallery', verbose_name='Albüm')),
            ],
            options={
                'db_table': 'AlbumPhoto',
            },
        ),
    ]
