# Generated by Django 4.1.7 on 2023-02-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumPhoto',
            new_name='GalleryPhoto',
        ),
        migrations.AlterModelTable(
            name='galleryphoto',
            table='GalleryPhoto',
        ),
    ]
