# Generated by Django 4.1.7 on 2023-02-21 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0002_rename_albumphoto_galleryphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='uploadfiles/Albümİmage'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='Cover',
            field=models.ImageField(blank=True, upload_to='uploadfiles/Albüm'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='PublishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='Title',
            field=models.CharField(max_length=255),
        ),
    ]
