# Generated by Django 4.1.7 on 2023-02-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComponentFile', models.CharField(max_length=45)),
                ('ComponentName', models.CharField(max_length=150)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsForUsers', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'Component',
            },
        ),
        migrations.CreateModel(
            name='ComponentsPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComponentLocation', models.CharField(choices=[('01H', 'Header'), ('02L', 'Left'), ('03C', 'Content'), ('04R', 'Right'), ('05F', 'Footer')], max_length=3)),
                ('ComponentOrder', models.IntegerField(default=0)),
                ('Component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='componentsofpage', to='componentApp.component')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.pages')),
            ],
            options={
                'db_table': 'ComponentsPages',
            },
        ),
    ]
