# Generated by Django 4.1.7 on 2023-02-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentspages',
            name='ComponentLocation',
            field=models.CharField(choices=[('01H', 'Header'), ('02L', 'Left'), ('03C', 'Content'), ('04R', 'Right')], max_length=3),
        ),
    ]
