# Generated by Django 4.1.7 on 2023-02-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genaralApp', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='IsActive',
            new_name='IsEnable',
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='IsDeleted',
            new_name='IsMenu',
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='Title',
            new_name='PageTitle',
        ),
        migrations.AddField(
            model_name='pages',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pages',
            name='IsUnit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='Keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pages',
            name='Language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='genaralApp.language'),
        ),
        migrations.AddField(
            model_name='pages',
            name='Layout',
            field=models.CharField(choices=[('_layout01.html', 'Layout-1'), ('_layout02.html', 'Layout-2'), ('_layout03.html', 'Layout-3')], default='_layout01.html', max_length=14),
        ),
        migrations.AddField(
            model_name='pages',
            name='PageFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.pages'),
        ),
        migrations.AddField(
            model_name='pages',
            name='PageName',
            field=models.SlugField(allow_unicode=True, default=2, max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='PageOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pages',
            name='PageRedirect',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='PageText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
