# Generated by Django 4.1.7 on 2023-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Text', models.TextField()),
                ('Description', models.TextField(blank=True, help_text='Bu kısım web sayfasında gözükmeyecektir. Sadece bilgilendirme amaçlıdır. ', null=True)),
                ('Image', models.ImageField(blank=True, upload_to='uploadfiles/sliderİmage')),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Slug', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Slider',
            },
        ),
    ]
