# Generated by Django 4.1.7 on 2023-02-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='Created_at',
            new_name='CreatedAt',
        ),
    ]
