# Generated by Django 4.1.7 on 2023-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_rename_created_at_slider_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Image',
            field=models.ImageField(blank=True, default='assets/img/slide/slide-1.jpg', upload_to='sliderImage'),
        ),
    ]
