# Generated by Django 4.1.6 on 2023-03-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_rename_created_at_slider_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Slug',
        ),
        migrations.AddField(
            model_name='slider',
            name='Order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Image',
            field=models.ImageField(blank=True, default='assets/img/slide/slide-1.jpg', upload_to='sliderImage'),
        ),
    ]
